### ISSUE TITLE
README section for windows

### ISSUE THREAD

**Issue by ZeeWanderer** [64/cmake-raytracer#14]
I am not sure how would you like to format this or if you would even want to include it at all hence an issue and not a pr.
### powershell:
```powershell
1, 2, 4, 8, 16, 32, 64, 128, 256, 512 | foreach {Write-Host $_; (Measure-Command { cmake . "-Dimage_width=$_" "-Dimage_height=$_" "-Dnum_procs=$Env:NUMBER_OF_PROCESSORS" 2> image_size_$_.ppm }).TotalSeconds }
```
---
### sample performance:
config: `i7-10700` 8C/16T with cmake `3.21.0-rc2` run for 16 threads . 

output:
```
1
3.3046483
2
3.2815196
4
3.381609
8
1.8510678
16
1.9677127
32
1.8989169
64
3.2966402
128
12.1628932
256
47.9041449
512
184.0473142
```

**Comment by 64** [comment]
Good idea 😁 I'd accept a PR for this -- you can just add 'powershell alternative: ...' or something below the existing Linux command.
