### ISSUE TITLE
Incorrect renderer

### ISSUE THREAD

**Issue by XRay3D** [64/cmake-raytracer#17]
You do not have a shadow in the reflection on the sphere, the shadow on the tile from the sphere. )))

**Comment by 64** [comment]
Yes, the shadow is faked. Proper shadow rays would make it a bit too slow so I just hacked something that would be believable (to the untrained eye 😉)

**Comment by XRay3D** [comment]
> Yes, the shadow is faked. Proper shadow rays would make it a bit too slow so I just hacked something that would be believable (to the untrained eye 😉)

In general, a cool example of using CMake. Thank you! Learned a lot of new syntax and usage, good tutorial.
