### ISSUE TITLE
Artifacts on the sample image

### ISSUE THREAD

**Issue by p4vook** [64/cmake-raytracer#3]
The sample image has some artifacts: for example, the part of the "floor" which is the nearest to the camera appears convex.

**Comment by 64** [comment]
Indeed - I haven't looked at the code in a while, but I'd suspect that it's due to how I generate the checkerboard pattern.

**Comment by fidergo-stephane-gourichon** [comment]
The checkerboard pattern does have a bug, but a different one.

**Comment by fidergo-stephane-gourichon** [comment]
Fixed that in #5.

> The checkerboard pattern does have a bug, but a different one.

Fixed that other bug in #4.

**Comment by fidergo-stephane-gourichon** [comment]
See [this comment](https://github.com/64/cmake-raytracer/pull/7#issuecomment-757564250-permalink) for result of merging #4, #5, #6 and #7.

You can thank https://news.ycombinator.com/item?id=25700038 .
